loops: libclassloops.a
	gcc -o loops -L. -lclassloops

libclassloops.a: basicClassification.o advancedClassificationLoop.o
	ar rcs libclassloops.a basicClassification.o advancedClassificationLoop.o

basicClassification.o: basicClassification.c NumClass.h
	gcc -c basicClassification.c

advancedClassificationLoop.o: advancedClassificationLoop.c NumClass.h
	gcc -c advancedClassificationLoop.c

recursives: libclassrec.a
	gcc -o recursives -L. -lclassrec

libclassrec.a: basicClassification.o advancedClassificationRecursion.o
	ar rcs libclassrec.a basicClassification.o advancedClassificationRecursion.o

advancedClassificationRecursion.o: advancedClassificationRecursion.c NumClass.h
	gcc -c advancedClassificationRecursion.c

recursived: libclassrec.so
	gcc -o recursived -L. -lclassrec

libclassrec.so: basicClassification.o advancedClassificationRecursion.o
	gcc -shared -o libclassrec.so basicClassification.o advancedClassificationRecursion.o

loopd: libclassloops.so
	gcc -o loopd -L. -lclassloops

libclassloops.so: basicClassification.o advancedClassificationLoop.o
	gcc -shared -o libclassloops.so basicClassification.o advancedClassificationLoop.o

mains: main.o libclassrec.a
	gcc -o mains main.o libclassrec.a

main.o: main.c NumClass.h
	gcc -c main.o main.c

maindloop: main.o loopd
	gcc -o maindloop main.o libclassloops.so

maindrec: main.o recursived
	gcc -o maindrec main.o libclassrec.so

all: mains maindrec maindloop

clean:
	rm -f *.a *.o *.so maindloop maindrec mains
